"""empty message

Revision ID: 136147402e96
Revises: 3228a3f5703f
Create Date: 2023-10-09 17:17:38.812480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136147402e96'
down_revision = '3228a3f5703f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('challenge', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('challenge')

    # ### end Alembic commands ###
