"""empty message

Revision ID: 3a62595d7aea
Revises: 380407bc4b90
Create Date: 2023-10-04 12:22:36.019956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a62595d7aea'
down_revision = '380407bc4b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_type', sa.String(length=50), nullable=True))

    with op.batch_alter_table('temp_match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_type', sa.String(length=50), nullable=True))
        batch_op.drop_column('is_confirmed')
        batch_op.drop_column('submit_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submit_by', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('is_confirmed', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('match_type')

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('match_type')

    # ### end Alembic commands ###
