"""empty message

Revision ID: 9094b0afbaf5
Revises: 7b2ccf771b03
Create Date: 2023-10-09 19:25:39.665305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9094b0afbaf5'
down_revision = '7b2ccf771b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('originator_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('notification_user_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('originator')
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('originator', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notification_user_fkey', 'user', ['user'], ['id'])
        batch_op.drop_column('originator_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
