"""empty message

Revision ID: a5e76c493981
Revises: 3a62595d7aea
Create Date: 2023-10-04 14:31:39.032104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e76c493981'
down_revision = '3a62595d7aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submit_by', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_match', schema=None) as batch_op:
        batch_op.drop_column('submit_by')

    # ### end Alembic commands ###
